export const transactionData = [
  {
    id: "1",
    transactionPrice: 12.99,
    transactionName: "Coffee Shop",
    transactionLocation: "San Francisco, CA",
    transactionDate: "10th April, 2023",
  },
  {
    id: "2",
    transactionPrice: 45.75,
    transactionName: "Tech Store",
    transactionLocation: "Austin, TX",
    transactionDate: "11th April, 2023",
  },
  {
    id: "3",
    transactionPrice: 32.50,
    transactionName: "Grocery Store",
    transactionLocation: "Miami, FL",
    transactionDate: "12th April, 2023",
  },
  {
    id: "4",
    transactionPrice: 20.99,
    transactionName: "Bookstore",
    transactionLocation: "Portland, OR",
    transactionDate: "13th April, 2023",
  },
  {
    id: "5",
    transactionPrice: 60.25,
    transactionName: "Clothing Store",
    transactionLocation: "Los Angeles, CA",
    transactionDate: "14th April, 2023",
  },
  {
    id: "6",
    transactionPrice: 25.49,
    transactionName: "Fast Food Restaurant",
    transactionLocation: "Houston, TX",
    transactionDate: "15th April, 2023",
  },
  {
    id: "7",
    transactionPrice: 35.99,
    transactionName: "Home Improvement Store",
    transactionLocation: "Seattle, WA",
    transactionDate: "16th April, 2023",
  },
  {
    id: "8",
    transactionPrice: 18.75,
    transactionName: "Pharmacy",
    transactionLocation: "Chicago, IL",
    transactionDate: "17th April, 2023",
  },
  {
    id: "9",
    transactionPrice: 50.00,
    transactionName: "Furniture Store",
    transactionLocation: "Denver, CO",
    transactionDate: "18th April, 2023",
  },
  {
    id: "10",
    transactionPrice: 27.99,
    transactionName: "Electronics Store",
    transactionLocation: "Boston, MA",
    transactionDate: "19th April, 2023",
  },
];
